server:
  port: 8083

spring:
  application:
    name: RecipeService

  datasource:
    url: jdbc:postgresql://localhost:5432/recipes
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        default_schema: recipeservice
        hbm2ddl:
          create_namespaces: true